Samples=(GTeLs_7 GTeLs_8 GP53eLs1_9 GP53eLs1_10 GP53eLs1_11 GP53eLsM_12)
DataDir=01.data
MappingDir=02.mapping
ResultDir=03.result
StatDir=0a.stat

mkdir ../$DataDir ../$MappingDir ../$ResultDir ../$StatDir

##========================data quality control and trim========================
for i in ${Samples[*]}
do
    fastp -i ../$DataDir/$i/${i}_R1.fq.gz -I ../$DataDir/$i/${i}_R2.fq.gz -o ../$DataDir/$i/${i}_trim_R1.fq.gz -O ../$DataDir/$i/${i}_trim_R2.fq.gz -f 10 -F 10 --html ../$DataDir/$i/${i}.trim.fastp.html --json ../$DataDir/$i/${i}.trim.fastp.json -w 16 -c
done
##=============================================================================
##==========================mapping to fusion genome===========================
for i in ${Samples[*]}
do
    Align.sh -I ~/data/ref_data/index/XenTr_v10.0_XenLa_v10.1_clean.bwa_index -1 ../$DataDir/$i/${i}_trim_R1.fq.gz -2 ../$DataDir/$i/${i}_trim_R2.fq.gz -o ../$MappingDir/$i -p $i -t 16
	bamCoverage -b ../$MappingDir/$i/$i.sort.rmdup.filter.bam -o ../$MappingDir/$i/$i.RPKM.bigwig --binSize 10 --normalizeUsing RPKM -p 8 --ignoreDuplicates
	bamCoverage -b ../$MappingDir/$i/$i.sort.rmdup.filter.bam -o ../$MappingDir/$i/$i.1M.RPKM.bigwig --binSize 1000000 --normalizeUsing RPKM -p 8 --ignoreDuplicates
	bigWigToBedGraph ../$MappingDir/$i/$i.1M.RPKM.bigwig ../$MappingDir/$i/$i.1M.RPKM.bedgraph
done
##=============================================================================
##circos figure generated by R script